/**
 * cards — Block Collection block generated by fast-track/blocks-from-proto.mjs. Generated
 * output: a fix is a seam answer or a generator change, then regeneration — never a hand edit.
 *
 * Content model: one row per card — image cell | text cell (title, copy, CTA).
 * decorate() MOVES each row into a list item (EW1), the cell wrappers carry the classes (EW2),
 * a linked title becomes the card link (EW6). Pictures are the pipeline's (R5), not re-built.
 */

// Moves every child element of cell into slot; the next sibling is read before the move (EW1).
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

// The card's <a> holding the unit's cells when its title was linked, else null.
function cardLink(unit) {
  const link = unit.querySelector(':is(h1, h2, h3, h4, h5, h6) > a[href]');
  if (!link) return null;
  const a = document.createElement('a');
  a.className = 'card-link';
  a.href = link.href;
  link.replaceWith(...link.childNodes);
  fill(a, unit);
  return a;
}

export default function decorate(block) {
  const list = document.createElement('div');
  list.className = 'cards-list';
  list.setAttribute('role', 'list');
  [...block.children].forEach((unit) => {
    const item = document.createElement('div');
    item.className = 'cards-card';
    item.setAttribute('role', 'listitem');
    const link = cardLink(unit);
    [...(link ?? unit).children].forEach((div) => {
      const media = div.children.length === 1 && div.querySelector('picture, img');
      div.className = media ? 'cards-card-image' : 'cards-card-body';
    });
    if (link) item.append(link);
    else fill(item, unit);
    list.append(item);
  });
  block.replaceChildren(list);
}
