/**
 * accordion — Block Collection block generated by fast-track/blocks-from-proto.mjs. Generated
 * output: a fix is a seam answer or a generator change, then regeneration — never a hand edit.
 *
 * Content model: one row per item — question cell | answer cell.
 * decorate() keeps the authored question in its own div (EW7 — no summary or button hosts
 * authored text) and adds a chevron button that toggles the answer; nodes are never rebuilt.
 */
export default function decorate(block) {
  [...block.children].forEach((item) => {
    const [label, body] = item.children;
    if (!label || !body) return;
    item.className = 'accordion-item';
    label.className = 'accordion-item-label';
    body.className = 'accordion-item-body';
    const toggle = document.createElement('button');
    toggle.type = 'button';
    toggle.className = 'accordion-item-toggle';
    toggle.setAttribute('aria-expanded', 'false');
    toggle.setAttribute('aria-label', 'Toggle answer');
    label.append(toggle);
    body.hidden = true;
    label.addEventListener('click', () => {
      const open = toggle.getAttribute('aria-expanded') === 'true';
      toggle.setAttribute('aria-expanded', String(!open));
      body.hidden = open;
    });
  });
}
