/**
 * header — template-slotted chrome block generated by fast-track/blocks-from-proto.mjs from the
 * prototype navbar. Generated output: a fix is a generator change, then regeneration — never a
 * hand edit.
 *
 * Content model: the /nav document, three sections in order — brand (<p><a
 * href="/">wordmark</a></p>), sections (<ul>, a nested <ul> per megamenu), tools (CTA
 * paragraphs). decorate() MOVES each section's authored nodes into the matching empty slot of
 * TEMPLATE (EW1); the slot wrappers carry the classes (EW2); the hamburger button hosts no
 * authored text (EW7).
 */
import { getMetadata } from '../../scripts/aem.js';
import { loadFragment } from '../fragment/fragment.js';

const SLOTS = ['brand', 'sections', 'tools'];
const TEMPLATE = [
  '<nav id="nav" aria-expanded="false"><div class="nav-hamburger">',
  '<button type="button" aria-controls="nav" aria-label="Open navigation">',
  '<span class="nav-hamburger-icon"></span></button></div>',
  '<div class="nav-brand" data-slot="brand">',
  '<svg width="100%" height="100%" viewBox="0 0 33 33" preserveAspectRatio="xMidYMid meet',
  '" aria-hidden="true">',
  '<path d="M28,0H5C2.24,0,0,2.24,0,5v23c0,2.76,2.24,5,5,5h23c2.76,0,5-2.24,5-5V5c0-2.76-',
  '2.24-5-5-5ZM29,17c-6.63,0-12,5.37-12,12h-1c0-6.63-5.37-12-12-12v-1c6.63,0,12-5.37,12-1',
  '2h1c0,6.63,5.37,12,12,12v1Z" fill="currentColor"></path></svg></div>',
  '<div class="nav-sections" data-slot="sections"></div>',
  '<div class="nav-tools" data-slot="tools"></div></nav>',
].join('');
const isDesktop = window.matchMedia('(min-width: 900px)');

// Moves every child element of cell into slot; the next sibling is read before the move.
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

function toggleMenu(nav, expanded = nav.getAttribute('aria-expanded') !== 'true') {
  nav.setAttribute('aria-expanded', String(expanded));
  document.body.style.overflowY = expanded && !isDesktop.matches ? 'hidden' : '';
  nav.querySelector('.nav-hamburger button')
    .setAttribute('aria-label', expanded ? 'Close navigation' : 'Open navigation');
}

function toggleDrop(nav, li) {
  const open = li.getAttribute('aria-expanded') === 'true';
  nav.querySelectorAll('.nav-drop').forEach((d) => d.setAttribute('aria-expanded', 'false'));
  li.setAttribute('aria-expanded', String(!open));
}

export default async function decorate(block) {
  const navMeta = getMetadata('nav');
  const navPath = navMeta ? new URL(navMeta, window.location).pathname : '/nav';
  const fragment = await loadFragment(navPath);
  const wrapper = document.createElement('div');
  wrapper.className = 'nav-wrapper';
  wrapper.innerHTML = TEMPLATE;
  const nav = wrapper.firstElementChild;
  SLOTS.forEach((name, i) => {
    const section = fragment?.children[i];
    if (!section) return;
    const cell = section.querySelector('.default-content-wrapper') || section;
    fill(nav.querySelector(`[data-slot="${name}"]`), cell);
  });
  nav.querySelectorAll('.nav-sections > ul > li').forEach((li) => {
    if (!li.querySelector('ul')) return;
    li.classList.add('nav-drop');
    li.setAttribute('aria-expanded', 'false');
    li.addEventListener('click', () => { if (isDesktop.matches) toggleDrop(nav, li); });
  });
  nav.querySelector('.nav-hamburger').addEventListener('click', () => toggleMenu(nav));
  toggleMenu(nav, false);
  isDesktop.addEventListener('change', () => toggleMenu(nav, false));
  block.replaceChildren(wrapper);
}
