/**
 * hero-section — template-slotted block generated by fast-track/blocks-from-proto.mjs from the
 * prototype section "hero-section". Generated output: a fix is a seam answer or a generator
 * change, then regeneration — never a hand edit.
 *
 * Content model: one row per slot in reading order — picture, eyebrow, heading, lead, ctas.
 * decorate() moves each cell's authored nodes into the matching empty slot of TEMPLATE (EW1); the
 * slot wrappers carry the layout classes (EW2); CTAs travel inside their paragraph (EW3); no
 * module state (EW9).
 */
const ROLES = ['picture', 'eyebrow', 'heading', 'lead', 'ctas'];
const TEMPLATE = [
  '<div class="inner"><div class="picture" data-slot="picture"></div>',
  '<div class="eyebrow" data-slot="eyebrow"></div>',
  '<div class="heading" data-slot="heading"></div><div class="lead" data-slot="lead">',
  '</div><div class="ctas" data-slot="ctas"></div></div>',
].join('');

// Moves every child element of cell into slot; the next sibling is read before the move.
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

export default async function decorate(block) {
  const tpl = document.createElement('div');
  tpl.innerHTML = TEMPLATE;
  const cells = [...block.querySelectorAll(':scope > div > div')];
  ROLES.forEach((role, i) => {
    const slot = tpl.querySelector(`[data-slot="${role}"]`);
    if (!slot || !cells[i]) return;
    fill(slot, cells[i]);
  });
  block.replaceChildren(...tpl.children);
}
