/**
 * tabs — Block Collection block generated by fast-track/blocks-from-proto.mjs. Generated
 * output: a fix is a seam answer or a generator change, then regeneration — never a hand edit.
 *
 * Content model: one row per tab — label cell | panel cell.
 * decorate() MOVES the label paragraph into a div[role=tab] (EW7 — no <button> hosts authored
 * text) and the panel content into a div[role=tabpanel]; a panel of cards (repeated headings)
 * is segmented into card items, a linked title becomes the card link (EW6).
 */

// Moves every child element of cell into slot; the next sibling is read before the move (EW1).
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

// The card's <a> holding the unit's cells when its title was linked, else null.
function cardLink(unit) {
  const link = unit.querySelector(':is(h1, h2, h3, h4, h5, h6) > a[href]');
  if (!link) return null;
  const a = document.createElement('a');
  a.className = 'card-link';
  a.href = link.href;
  link.replaceWith(...link.childNodes);
  fill(a, unit);
  return a;
}

// A panel whose headings repeat is a card list: media and text before a heading buffer into
// the item that heading opens.
function segmentCards(panel) {
  const heads = [...panel.querySelectorAll(':scope > :is(h2, h3, h4, h5)')];
  const tag = heads[0]?.tagName;
  if (heads.filter((h) => h.tagName === tag).length < 2) return;
  const list = document.createElement('div');
  list.className = 'tabs-cards';
  list.setAttribute('role', 'list');
  let item = null;
  let node = panel.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    if (!item || (item.querySelector(tag) && node.querySelector('picture, img'))) {
      item = document.createElement('div');
      item.className = 'tabs-card';
      item.setAttribute('role', 'listitem');
      list.append(item);
    }
    item.append(node);
    node = next;
  }
  [...list.children].forEach((card) => {
    const link = cardLink(card);
    if (link) card.append(link);
  });
  panel.append(list);
}

function select(block, i) {
  block.querySelectorAll('[role="tab"]').forEach((t, j) => {
    t.setAttribute('aria-selected', String(i === j));
    t.tabIndex = i === j ? 0 : -1;
  });
  block.querySelectorAll('[role="tabpanel"]').forEach((p, j) => { p.hidden = i !== j; });
}

export default function decorate(block) {
  const list = document.createElement('div');
  list.className = 'tabs-list';
  list.setAttribute('role', 'tablist');
  const panels = [];
  [...block.children].forEach((item, i) => {
    const [label, panel] = item.children;
    if (!label || !panel) return;
    const tab = document.createElement('div');
    tab.className = 'tabs-tab';
    tab.setAttribute('role', 'tab');
    tab.id = `tab-${i}`;
    tab.setAttribute('aria-controls', `tabpanel-${i}`);
    fill(tab, label);
    tab.addEventListener('click', () => select(block, i));
    tab.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' ') select(block, i);
    });
    list.append(tab);
    panel.className = 'tabs-panel';
    panel.setAttribute('role', 'tabpanel');
    panel.id = `tabpanel-${i}`;
    panel.setAttribute('aria-labelledby', tab.id);
    segmentCards(panel);
    panels.push(panel);
  });
  block.replaceChildren(list, ...panels);
  select(block, 0);
}
