/*
 js-cookie v3.0.5 | MIT */
'use strict';var headlibs=headlibs||{};(function(){headlibs.version=1})();$(document).ready(function(){initTopNav()});
function initTopNav(){function m(a){if(!g){var b=a.data("menu");b=k.find('.dropdown[data-menu\x3d"'+b+'"]');if(b.length){e.find(".has-dropdown").removeClass("active");a.addClass("active");var c=b.outerWidth(),l=b.outerHeight();{const y=b.find(".component-subnav").data("total-columns");var t=b.outerWidth();const A=$(window).width();var v=$(".site-wrapper").length?$(".site-wrapper").offset().left:0;const B=a.offset().left-v;t=(A-t)/2-v;v=B+a.width()/2-p.width()/2;p.css({left:v+"px",top:"-12px"});a.is(":last-child")&&
b.find(".col:last-child").hasClass("light-grey-bg")?p.addClass("light-grey-fill"):p.removeClass("light-grey-fill");a=["three-column","five-column"].includes(y)||1600>A&&"two-column"!==y?t:B+({"two-column":0,"two-column-simple":-114}[y]||0)}k.addClass("active").css({width:c,height:l,transform:"translateX("+a+"px)",transition:q?"none":""});q=!1;k.find(".dropdown").removeClass("active");b.addClass("active");d.addClass("active")}}}function n(a,b,c,l){return window.location.pathname.startsWith("/content/synopsys")?
a.replace(b,c):"/en-us"===b?"/"===window.location.pathname?window.location.origin+c+".html":window.location.origin+c+window.location.pathname:"/en-us"===c?1<window.location.pathname.split("/").length-1?window.location.origin+window.location.pathname.replace(b,c):window.location.origin:a.replace(b,c)}function h(a){return 0<=a.indexOf("/ja-jp")?"ja-jp":0<=a.indexOf("/zh-cn")?"zh-cn":0<=a.indexOf("/zh-tw")?"zh-tw":0<=a.indexOf("/ko-kr")?"ko-kr":"en-us"}$(".cmp-experiencefragment--topnav").parent().addClass("sticky-nav");
window.onscroll=function(){80<document.body.scrollTop||80<document.documentElement.scrollTop?$("#topNav").addClass("overlapping"):$("#topNav").removeClass("overlapping")};const e=$("#topNav"),k=$(".dropdown-list"),d=$("#morph-dropdown-wrapper"),p=d.find(".triangle");let f,q=!0,g=1129>$(window).width(),w;const r=()=>{k.removeClass("active");e.find(".has-dropdown").removeClass("active");k.css({height:"auto",width:"auto"});d.removeClass("active");e.removeClass("active-dropdown");$(".component-nav-list.active").removeClass("active");
p.css({top:"0"})};e.on("mouseenter",".has-dropdown",function(){g||(clearTimeout(f),m($(this)))});e.on("focusin",".has-dropdown \x3e .main-nav-item-header",function(){g||(clearTimeout(f),m($(this).closest(".has-dropdown")))});e.on("focusout",function(a){g||setTimeout(()=>{$(document.activeElement).closest(".main-nav").length||(clearTimeout(f),f=setTimeout(r,100))},50)});e.on("mouseleave",".main-nav",function(){g||(f=setTimeout(r,150))});k.on("mouseenter",()=>clearTimeout(f)).on("mouseleave",()=>{g||
(f=setTimeout(r,150))});e.on("click",".has-dropdown",function(a){if(g){a.preventDefault();a=$(this);var b=a.data("menu");b=k.find('.dropdown[data-menu\x3d"'+b+'"]');b.length&&(e.find(".has-dropdown").removeClass("active"),a.addClass("active"),e.addClass("active-dropdown"),$("#morph-dropdown-wrapper").scrollTop(0),k.find(".dropdown").removeClass("active"),b.addClass("active"),d.addClass("active"),a=d.find(".component-subnav[data-total-columns\x3d'three-column'] .header-item.no-header"),a.length&&(a=
a.closest(".col"),a.css("margin-top",0),a.prev().css("border","none"),a.prev().css("padding-bottom","8px")),a=d.find(".component-subnav .component-topNavAd.hideOnMobile"),a.length&&0===a.next().length&&a.closest(".col").prev().css("border-bottom","none"))}});$(".component-subnav[data-total-columns\x3d'five-column']").on("click",".header-item",function(a){if(g){a.preventDefault();a=$(this).parent();var b=a.hasClass("active");$(".component-nav-list.active").removeClass("active");b||a.addClass("active");
this.hasAttribute("href")&&$(this).attr("href")&&!$(this).siblings(".nav-list").find("li:first-child").hasClass("duplicate-header-item")&&(a=$('\x3cli class\x3d"duplicate-header-item"\x3e'),b=$(this).clone(),b.empty(),b.removeClass("header-item").addClass("hasSubtitle"),b.append('\x3cdiv class\x3d"nav-item-title"\x3e'+this.innerText+"\x3c/div\x3e"),b.append('\x3cspan class\x3d"nav-item-subtitle"\x3e'+$(this).find(".nav-list-header-subtitle").text()+"\x3c/span\x3e"),a.append(b),$(this).siblings(".nav-list").prepend(a))}});
e.on("click",".navbar-toggler",function(){$(".component-nav-top, html").toggleClass("removeScroll mobile-menu-opened");d.removeClass("active");e.removeClass("active-dropdown")}).on("click",".back",()=>r());$(window).on("resize",function(){const a=1129>$(window).width();a!==g&&(g=a,r(),$(".component-nav-top, html").removeClass("removeScroll mobile-menu-opened"),q=!0);$(".component-nav-top").addClass("no-transition");clearTimeout(w);w=setTimeout(()=>{$(".component-nav-top").removeClass("no-transition")},
250)});let z=0,C=0;d.on("touchstart",a=>{z=a.originalEvent.touches[0].clientX;C=a.originalEvent.touches[0].clientY}).on("touchend",a=>{const b=a.originalEvent.changedTouches[0].clientY;50<a.originalEvent.changedTouches[0].clientX-z&&50>Math.abs(b-C)&&(d.removeClass("active"),e.removeClass("active-dropdown"))});$(document).on("click",a=>{!$(a.target).closest("#coveo-search-wrapper, .icon-search, #onetrust-banner-sdk").length&&$("html").hasClass("removeScroll")&&($("#coveo-search-wrapper, .component-nav-top").removeClass("active search-opened"),
g||($(".component-nav-top, html").removeClass("removeScroll mobile-menu-opened"),$("#modal-overlay-coveo-search").removeClass("active")))});$(document).keyup(function(a){"Escape"===a.key&&$("html").hasClass("removeScroll")&&($("#coveo-search-wrapper, .component-nav-top").removeClass("active search-opened"),g||($(".component-nav-top, html").removeClass("removeScroll mobile-menu-opened"),$("#modal-overlay-coveo-search").removeClass("active")))});e.on("click",".icon-search, #coveo-search-wrapper .close",
function(a){a.stopPropagation();$("#coveo-search-wrapper, .component-nav-top").toggleClass("active search-opened");g||($("#modal-overlay-coveo-search").toggleClass("active"),$(".component-nav-top, html").toggleClass("removeScroll mobile-menu-opened"))});const x=$(".carousel-holder");var u=$("body[data-page-type\x3d'home-page']");if(x.length&&u.length){function a(c){c=c.find(".slick-current.slick-active .carousel-wrapper-hp");c.length&&(c=c.attr("data-color-theme")||"",$("body #topNav").attr("data-color-theme",
c))}function b(c){(new MutationObserver(function(){a(c)})).observe(c[0],{subtree:!0,attributes:!0,attributeFilter:["class"]})}u=x.find(".slick-track");u.length?(a(u),b(u)):(new MutationObserver(function(c,l){c=x.find(".slick-track");c.length&&(l.disconnect(),a(c),b(c))})).observe(x[0],{childList:!0,subtree:!0})}$('.component-subnav[data-total-columns\x3d"three-column"] .light-grey-bg').each(function(a,b){$(this).find(".component-nav-list")?$(this).removeClass("align-items-center"):""});const E=["/content/synopsys/en-us.html",
"/content/synopsys/ja-jp.html","/content/synopsys/zh-cn.html","/content/synopsys/zh-tw.html","/content/synopsys/ko-kr.html"];$(".global-nav-link-list .dropdown-item").filter((a,b)=>E.includes($(b).attr("data-link"))).each((a,b)=>{$(b).addClass("global-nav-link")});var D=window.location.href;$(".global-nav-link-list .dropdown-item").on("click",function(a){a.preventDefault();var b=$(this).attr("data-link");a=b.substring(b.lastIndexOf("/"),b.lastIndexOf("."));var c=D.toString(),l="";a!=="/"+h(c)&&(l=
0<=c.indexOf("/ja-jp")?n(c,"/ja-jp",a,$(this)):0<=c.indexOf("/zh-cn")?n(c,"/zh-cn",a,$(this)):0<=c.indexOf("/zh-tw")?n(c,"/zh-tw",a,$(this)):0<=c.indexOf("/ko-kr")?n(c,"/ko-kr",a,$(this)):n(c,"/en-us",a,$(this)),console.log("Top Nav \u2192 Trying to go here:",l),$.ajax({url:l,type:"HEAD",error:function(){console.log("Top Nav \u2192 Page does not exists in that local language. Redirecting to homepage:",b);window.location.href=b},success:function(){var t=!l.includes("/content/synopsys")&&l.includes("/en-us")?
l.replace("/en-us",""):l;console.log("Top Nav \u2192 Page exists! Redirecting:",t);window.location.href=t}}))});$(".global-nav-link-list a.dropdown-item").each(function(){var a=$(this),b=a.attr("data-link"),c=b.lastIndexOf("/"),l=b.lastIndexOf(".");b.substring(c+1,l)===h(D)&&(a.closest("li").addClass("active"),$(".topbar-lang").text(a.text()))})}var jq3=$;
(function(m,n){"object"===typeof exports&&"undefined"!==typeof module?module.exports=n():"function"===typeof define&&define.amd?define(n):(m="undefined"!==typeof globalThis?globalThis:m||self,function(){var h=m.Cookies,e=m.Cookies=n();e.noConflict=function(){m.Cookies=h;return e}}())})(this,function(){function m(h){for(var e=1;e<arguments.length;e++){var k=arguments[e],d;for(d in k)h[d]=k[d]}return h}function n(h,e){function k(d,p,f){if("undefined"!==typeof document){f=m({},e,f);"number"===typeof f.expires&&
(f.expires=new Date(Date.now()+864E5*f.expires));f.expires&&(f.expires=f.expires.toUTCString());d=encodeURIComponent(d).replace(/%(2[346B]|5E|60|7C)/g,decodeURIComponent).replace(/[()]/g,escape);var q="",g;for(g in f)f[g]&&(q+="; "+g,!0!==f[g]&&(q+="\x3d"+f[g].split(";")[0]));return document.cookie=d+"\x3d"+h.write(p,d)+q}}return Object.create({set:k,get:function(d){if("undefined"!==typeof document&&(!arguments.length||d)){for(var p=document.cookie?document.cookie.split("; "):[],f={},q=0;q<p.length;q++){var g=
p[q].split("\x3d"),w=g.slice(1).join("\x3d");try{var r=decodeURIComponent(g[0]);f[r]=h.read(w,r);if(d===r)break}catch(z){}}return d?f[d]:f}},remove:function(d,p){k(d,"",m({},p,{expires:-1}))},withAttributes:function(d){return n(this.converter,m({},this.attributes,d))},withConverter:function(d){return n(m({},this.converter,d),this.attributes)}},{attributes:{value:Object.freeze(e)},converter:{value:Object.freeze(h)}})}return n({read:function(h){'"'===h[0]&&(h=h.slice(1,-1));return h.replace(/(%[\dA-F]{2})+/gi,
decodeURIComponent)},write:function(h){return encodeURIComponent(h).replace(/%(2[346BF]|3[AC-F]|40|5[BDE]|60|7[BCD])/g,decodeURIComponent)}},{path:"/"})});