/**
 * footer — template-slotted block generated by fast-track/blocks-from-proto.mjs from the
 * prototype section "footer". Generated output: a fix is a seam answer or a generator change,
 * then regeneration — never a hand edit.
 *
 * Content model: one row per slot in reading order — body, items. decorate() moves each cell's
 * authored nodes into the matching empty slot of TEMPLATE (EW1); the slot wrappers carry the
 * layout classes (EW2); CTAs travel inside their paragraph (EW3); no module state (EW9).
 */
import { getMetadata } from '../../scripts/aem.js';
import { loadFragment } from '../fragment/fragment.js';

const ROLES = ['body', 'items'];
const TEMPLATE = [
  '<div class="inner">',
  '<svg width="100%" height="100%" viewBox="0 0 33 33" preserveAspectRatio="xMidYMid meet',
  '" aria-hidden="true">',
  '<path d="M28,0H5C2.24,0,0,2.24,0,5v23c0,2.76,2.24,5,5,5h23c2.76,0,5-2.24,5-5V5c0-2.76-',
  '2.24-5-5-5ZM29,17c-6.63,0-12,5.37-12,12h-1c0-6.63-5.37-12-12-12v-1c6.63,0,12-5.37,12-1',
  '2h1c0,6.63,5.37,12,12,12v1Z" fill="currentColor"></path></svg>',
  '<div class="body" data-slot="body"></div><div class="items" data-slot="items"></div>',
  '</div>',
].join('');
const ITEM = '<div class="item"></div>';
const ITEM_TAG = 'h4';
const MEDIA_LEADS = false;

// Moves every child element of cell into slot; the next sibling is read before the move.
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

// One item per ITEM_TAG heading (a picture opens the next item when MEDIA_LEADS): each run of
// authored siblings moves into a fresh, empty ITEM clone — nothing is rebuilt or copied.
function fillItems(slot, cell) {
  let item = null;
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    const opens = node.matches(ITEM_TAG)
      || (MEDIA_LEADS && !!(node.matches('picture, img') || node.querySelector('picture, img')));
    if (!item || (opens && item.querySelector(ITEM_TAG))) {
      const holder = document.createElement('div');
      holder.innerHTML = ITEM;
      item = holder.firstElementChild;
      slot.append(item);
    }
    item.append(node);
    node = next;
  }
}

export default async function decorate(block) {
  const meta = getMetadata('footer');
  const path = meta ? new URL(meta, window.location).pathname : '/footer';
  const fragment = await loadFragment(path);
  const tpl = document.createElement('div');
  tpl.innerHTML = TEMPLATE;
  const cells = [...(fragment ? fragment.children : [])]
    .map((s) => s.querySelector('.default-content-wrapper') || s);
  ROLES.forEach((role, i) => {
    const slot = tpl.querySelector(`[data-slot="${role}"]`);
    if (!slot || !cells[i]) return;
    (role === 'items' ? fillItems : fill)(slot, cells[i]);
  });
  block.replaceChildren(...tpl.children);
}
