/**
 * inverse-section — template-slotted block generated by fast-track/blocks-from-proto.mjs from the
 * prototype section "inverse-section". Generated output: a fix is a seam answer or a generator
 * change, then regeneration — never a hand edit.
 *
 * Content model: one row per slot in reading order — heading, items. decorate() moves each cell's
 * authored nodes into the matching empty slot of TEMPLATE (EW1); the slot wrappers carry the
 * layout classes (EW2); CTAs travel inside their paragraph (EW3); no module state (EW9).
 */
const ROLES = ['heading', 'items'];
const TEMPLATE = [
  '<div class="inner"><div class="heading" data-slot="heading"></div>',
  '<div class="items" data-slot="items"></div></div>',
].join('');
const ITEM = '<div class="item"></div>';
const ITEM_TAG = 'h3';
const MEDIA_LEADS = false;

// Moves every child element of cell into slot; the next sibling is read before the move.
function fill(slot, cell) {
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    slot.append(node);
    node = next;
  }
}

// One item per ITEM_TAG heading (a picture opens the next item when MEDIA_LEADS): each run of
// authored siblings moves into a fresh, empty ITEM clone — nothing is rebuilt or copied.
function fillItems(slot, cell) {
  let item = null;
  let node = cell.firstElementChild;
  while (node) {
    const next = node.nextElementSibling;
    const opens = node.matches(ITEM_TAG)
      || (MEDIA_LEADS && !!(node.matches('picture, img') || node.querySelector('picture, img')));
    if (!item || (opens && item.querySelector(ITEM_TAG))) {
      const holder = document.createElement('div');
      holder.innerHTML = ITEM;
      item = holder.firstElementChild;
      slot.append(item);
    }
    item.append(node);
    node = next;
  }
}

export default async function decorate(block) {
  const tpl = document.createElement('div');
  tpl.innerHTML = TEMPLATE;
  const cells = [...block.querySelectorAll(':scope > div > div')];
  ROLES.forEach((role, i) => {
    const slot = tpl.querySelector(`[data-slot="${role}"]`);
    if (!slot || !cells[i]) return;
    (role === 'items' ? fillItems : fill)(slot, cells[i]);
  });
  block.replaceChildren(...tpl.children);
}
